Accounts/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'Accounts'

urlpatterns = [
    path('', views.accounts_home, name='accounts_home'),
    path('signup', views.signup_view, name='signup'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
]

urlpatterns += staticfiles_urlpatterns()

Blog/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from django.conf.urls.static import static
# from django.conf import settings


app_name = 'Blog'

urlpatterns = [
    path('', views.blog_home, name='blog_list'),
    path('create', views.create_article, name='create_article'),
    path('<slug>', views.article, name='article_selected'),
]

urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MySite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns  # for Static Files
from django.conf.urls.static import static  # for Save Image
from django.conf import settings  # for Save Image

urlpatterns = [
    path('', views.main_page, name='main'),
    path('admin/', admin.site.urls, name='admin'),
    path('about', views.about, name='about'),
    path('blog/', include('Blog.urls')),
    path('user/', include('Accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Accounts/models.py
from django.db import models

# Create your models here.

Blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    slug = models.SlugField()
    date_created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title
    def body_preview(self):
        return self.body[:50] + ' ...'

Blog/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'slug', 'body', 'image']

Accounts/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('Blog:blog_list')
    else:
        form = UserCreationForm()
    args = {'form': form}
    return render(request, 'Accounts/Signup.html', args)


def accounts_home(request):
    return render(request, 'Accounts/AccountsHome.html')


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('Blog:blog_list')
    else:
        form = AuthenticationForm()
    args = {'form': form}
    return render(request, 'Accounts/Login.html', args)


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return render(request, 'Accounts/Logout.html')

Blog/views.py
from django.shortcuts import render, redirect
from . import models
from django.contrib.auth.decorators import login_required
from . import forms


def blog_home(request):
    articles_obj = models.Article.objects.all().order_by('date_created')
    args = {'articles_obj': articles_obj}
    return render(request, 'Blog/BlogHome.html', args)


def article(request, slug):
    article_selected = models.Article.objects.get(slug=slug)
    args = {'article_selected': article_selected}
    return render(request, 'Blog/Article.html', args)


@login_required(login_url='Accounts:login')
def create_article(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            form_ins = form.save(commit=False)
            form_ins.author = request.user
            form.save()
            return redirect('Blog:blog_list')
    else:
        form = forms.CreateArticle()
    args = {'form': form}
    return render(request, 'Blog/CreateArticle.html', args)

MySite/views.py
from django.shortcuts import render

def main_page(reqquest):
    return render(reqquest, 'MainPage.html')

def about(request):
    return render(request, 'About.html')

Accounts/templates/Accounts/AccountsHome.html
{% extends 'Base.html' %}

{% block title %}Accounts{% endblock %}


{% block body %}
<p></p>
{% if user.is_authenticated %}
<h1>You are already logged in.</h1>
<meta http-equiv="refresh" content="3;url={% url 'Blog:blog_list' %}" />
{% else %}
<p>Please Login or Signup.</p>
{% endif %}
{% endblock %}

Accounts/templates/Accounts/Login.html
{% extends 'Base.html' %}

{% block title %}Login ...{% endblock %}

{% block body %}
<form action="" method="post">
    {{ form }}
    {% csrf_token %}
    {% if 'next' in request.GET %}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Login">
</form>
{% endblock %}

Accounts/templates/Accounts/Logout.html
{% extends 'Base.html' %}

{% block title %}You are Logged out.{% endblock %}

{% block body %}
<h1>You are Logged out.</h1>
<meta http-equiv="refresh" content="3;url={% url 'Blog:blog_list' %}" />
{% endblock %}

Accounts/templates/Accounts/Signup.html
{% extends 'Base.html' %}

{% block title %}SignUp ...{% endblock %}

{% block body %}
<form action="" method="post">
    {{form}}
    {% csrf_token %}
    <input type="submit" value="Submit">
</form>
{% endblock %}

Blog/templates/Blog/Article.html
{% extends 'Base.html' %}


{% block title %}{{ article_selected.title }}{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
<h1>{{ article_selected.title }}</h1><br>
<img src="{{ article_selected.image.url }}" alt=""><br><br>
<h2>{{ article_selected.body }}</h2><br>
<h3>Written by: {{ article_selected.author }}</h3>
<h3>{{ article_selected.date_created }}</h3>
{% endblock %}

Blog/templates/Blog/BlogHome.html
{% extends 'Base.html' %}


{% block title %}Blog{% endblock %}


{% block head %}
{% endblock %}


{% block body %}

<h1>Blog Home Page</h1><br><br>
{% for article in articles_obj %}
<h2><a href="{% url 'Blog:article_selected' slug=article.slug %}" target="_blank">{{ article.title }}</a></h2>
<h3>{{ article.body_preview }}</h3>
<h3>Written by: {{ article.author }}</h3>
<h4>{{ article.date_created }}</h4>
<p></p>
{% endfor %}

{% endblock %}

Blog/templates/Blog/CreateArticle.html
{% extends 'Base.html' %}

{% block title %}Create Article{% endblock %}

{% block body %}
<h1>Create Your Article ...</h1>
<form action="" method="post" enctype="multipart/form-data">
    {{ form }}
    {% csrf_token %}
    <input type="submit" value="Create">
</form>
{% endblock %}

templates/About.html
{% extends 'Base.html' %}

{% block title %}About{% endblock %}

{% block body %}
<h1>About</h1>
{% endblock %}

templates/Base.html
<!DOCTYPE html>
{% block out_html %}
{% endblock %}

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block head %}

    {% endblock %}
</head>
<body>
    <h1><a href="{% url 'Blog:blog_list' %}" target="_blank">Logo</a></h1>
    <nav>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <form action="{% url 'Accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
            </li>
            <li>
                <a href="{% url 'Blog:create_article' %}">Create Article</a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'Accounts:login' %}">Login</a>
            </li>
            <li>
                <a href="{% url 'Accounts:signup' %}">Signup</a>
            </li>
            {% endif%}
        </ul>
    </nav>
    <p></p>
    {% block body %}

    {% endblock %}
</body>
</html>

templates/MainPage.html
{% extends 'Base.html' %}

{% block title %}Home{% endblock %}

{% block body %}
<h1>Home Page</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{%block OutHtml%}
{%endblock%}

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%block Title%}{%endblock%}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {%block Head%}

    {%endblock%}
</head>
<body>
    <h1><a href="{%url 'Main'%}">Logo</a></h1>
    <nav>
        <ul>
            <li>
                <form action="{% url 'Accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
            </li>
        </ul>
    </nav>
    <p></p>
    {%block Body%}

    {%endblock%}
</body>
</html>